server:
  port: 18080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    metrics-topic: ${KAFKA_METRICS_TOPIC}
    init-topic: ${KAFKA_INIT_TOPIC}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
      properties:
        max.block.ms: 2000

agent:
  organization: ${ORGANIZATION}
  kafka-init-topic: ${KAFKA_INIT_TOPIC}
  collection-interval-ms: ${COLLECTION_INTERVAL_MS}
  time:
    continuous: ${CONTINUOUS}
    start: ${START_TIME}
    end: ${END_TIME}